### ISSUE TITLE
It has been fixed today

### ISSUE THREAD

**Issue by JiaPai12138** [ekknod/logitech-cve#10]
Now this cve (if just want to control mouse) was fixed in the latest release, version 2022.3.23
mouse action using this repo will not work anymore. Unless you don't update Ghub

**Comment by heiybb** [comment]
> Now this cve (if just want to control mouse) was fixed in the latest release, version 2022.3.23 mouse action using this repo will not work anymore. Unless you don't update Ghub

You still can install a old version GHUB to keep cve working.
https://www.reddit.com/r/LogitechG/comments/ltovos/how_to_install_old_ghub_works_no_auto_update/
This specific installer allows you install an old version GHUB(version:2020.10.6293) and won't update itself when installation finished.

**Comment by JiaPai12138** [comment]
> > Now this cve (if just want to control mouse) was fixed in the latest release, version 2022.3.23 mouse action using this repo will not work anymore. Unless you don't update Ghub
> 
> You still can install a old version GHUB to keep cve working. https://www.reddit.com/r/LogitechG/comments/ltovos/how_to_install_old_ghub_works_no_auto_update/ This specific installer allows you install an old version GHUB(version:2020.10.6293) and won't update itself when installation finished.

Yeah many thanks!
