### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by juauzynhu** [ekknod/logitech-cve#11]
How to pass negative values, like moving X to left, like -150?

**Comment by juauzynhu** [comment]
Or if its possible to pass higher values than char limits (-128 to 127).

**Comment by happymaj00r** [comment]
> Or if its possible to pass higher values than char limits (-128 to 127).

well just split it for example -150 would be -128 and -22)

**Comment by whiteCupz** [comment]
> > Or if its possible to pass higher values than char limits (-128 to 127).
> 
> well just split it for example -150 would be -128 and -22)

how you did that ,can you show me your code!
