### ISSUE TITLE
is this relative move ?

### ISSUE THREAD

**Issue by JuZi233** [ekknod/logitech-cve#16]
it seems to be a relative move. If I install different versions of ghub and one of them meets the requirements of this project, can this project still work properly?

**Comment by Chaoses-Ib** [comment]
Both answers are yes. However, as far as I know, there is now no way to install the old version that works. But you can use my [IbInputSimulator](https://github.com/Chaoses-Ib/IbInputSimulator) to use the drivers of Logitech Gaming Software and Razer Synapse 3.

**Comment by JuZi233** [comment]
> Both answers are yes. However, as far as I know, there is now no way to install the old version that works. But you can use my [IbInputSimulator](https://github.com/Chaoses-Ib/IbInputSimulator) to use the drivers of Logitech Gaming Software and Razer Synapse 3.

thanks.
